version: "3.8"

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: go-figure-db
    environment:
      POSTGRES_USER: gofigure
      POSTGRES_PASSWORD: gofigure
      POSTGRES_DB: go-figure-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      DATABASE_URL: postgres://gofigure:gofigure@postgres:5432/go-figure-db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
